# conda env for binder
name: sk-eval

channels:
  - conda-forge

dependencies:
  - python=3.8
  - lxml # for pandas.read_html, used in NotebookCollection
  - pip
  - pip:
    # Binder docs say setup.py is automatically installed but it's not working
    - git+https://github.com/ploomber/sklearn-evaluation
    # NotebookCollection example
    - jupytext
    - papermill
    - seaborn