# conda env for binder
name: sk-eval

channels:
  - conda-forge

dependencies:
  - python=3.10
  - lxml # for pandas.read_html, used in NotebookCollection
  - pip
  - scikit-learn>=1.2
  - matplotlib
  - pip:
    - sklearn-evaluation
    # NotebookCollection example
    - jupytext
    - papermill
    - seaborn
    - ipywidgets
    - jupysql