name: ske-doc

channels:
  - conda-forge


dependencies:
  - python=3.10
  - pip
  # install if with conda, pip fails when executed on Apple ARM
  - tensorflow=2.10.0
  # for pandas.read_html (optional dependency for NotebookCollection)
  - lxml
  - pip:
    - jupyter-book
    - jupytext
    - seaborn
    - ploomber-engine
    - jupysql
    - keras
    - pkgmt>=0.1.7
    - altair
    - lxml
    - -e ..

