title: sklearn-evaluation
author: Ploomber
copyright: 'Ploomber'
logo: logo.jpeg
execute:
  execute_notebooks: force
sphinx:
  extra_extensions:
    - matplotlib.sphinxext.plot_directive
    - IPython.sphinxext.ipython_console_highlighting
    - IPython.sphinxext.ipython_directive
    - sphinx.ext.autodoc
    - sphinx.ext.autosummary
    - sphinx.ext.intersphinx
    - sphinx.ext.napoleon
    #- sphinx_book_theme
  config:
    #html_theme: sphinx-book-theme
    html_show_copyright: True
    plot_include_source: True
    plot_html_show_formats: False
    plot_html_show_source_link: False
    intersphinx_mapping:
      sklearn:
        - "http://scikit-learn.org/stable"
        - null
      matplotlib:
        - "http://matplotlib.org/"
        - null
    execution_allow_errors: True
    execution_timeout: 1000
    suppress_warnings: ['myst.domains', 'myst.header']
    exclude_patterns: ['README.md']


# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# # Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib


repository:
  url: https://github.com/ploomber/sklearn-evaluation
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)


html:
  use_issues_button: true
  use_repository_button: true

