title: sklearn-evaluation
author: Eduardo Blancas Reyes
copyright: 'Copyright 2016, Eduardo Blancas Reyes.'
logo: logo.jpeg
execute:
  execute_notebooks: force
launch_buttons:
  binderhub_url: https://mybinder.org
sphinx:
  extra_extensions:
    - matplotlib.sphinxext.plot_directive
    - IPython.sphinxext.ipython_console_highlighting
    - IPython.sphinxext.ipython_directive
    - sphinx.ext.autodoc
    - sphinx.ext.autosummary
    - sphinx.ext.intersphinx
    - sphinx.ext.napoleon
  config:
    templates_path: ['_templates']
    html_show_copyright: false
    version: 0.8.3
    plot_include_source: True
    plot_html_show_formats: False
    plot_html_show_source_link: False
    htmlhelp_basename: sklearn-evaluationdoc
    intersphinx_mapping:
      sklearn:
        - "http://scikit-learn.org/stable"
        - null
      matplotlib:
        - "http://matplotlib.org/"
        - null
html:
  extra_footer: |
    <p>
    Copyright 2016, Eduardo Blancas Reyes.
    </p>

# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# # Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib


repository:
  url: https://github.com/ploomber/ploomber
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  #branch: master  # Which branch of the repository should be used when creating links (optional)


html:
  use_issues_button: true
  use_repository_button: true
