name: CI

on: [push, pull_request]
jobs:
  unit:
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Lint
      shell: bash -l {0}
      run: |
        pip install pkgmt
        pkgmt lint

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PLOOMBER_STATS_ENABLED: false
        PYTHON_VERSION: ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        # if we remove the --editable flag pytest throws an error, because there
        # are two copies of the pkg (src/ and site-packages/), this is a quick
        # way to fix it
        # https://github.com/pytest-dev/pytest/issues/7678
        pip install --editable .
        python -c "import sklearn_evaluation"
        pip install --editable ".[dev]"

        pytest tests/ src/ --cov=sklearn_evaluation --doctest-modules --durations-min=5
        coveralls

  # run: pkgmt check
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pkgmt[check]'
      - name: Check project
        run: |
          pkgmt check
